CREATE TABLE `clientes` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `tipoDocumento` varchar(1) NOT NULL,
  `letraDni` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `fechaAlta` date NOT NULL DEFAULT (curdate()),
  `nombre` varchar(25) NOT NULL,
  `apellidos` varchar(25) NOT NULL,
  `direccion` varchar(45) NOT NULL,
  `codigoPostal` int NOT NULL,
  `telefono` varchar(12) NOT NULL,
  `email` varchar(40) DEFAULT NULL,
  `tieneTarjeta` int NOT NULL,
  `tienePlazoFijo` int NOT NULL,
  `tieneCredito` int NOT NULL,
  `tieneHipoteca` int NOT NULL,
  `numeroDocumento` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `cliente_tiposDocumento_FK` (`tipoDocumento`),
  CONSTRAINT `cliente_tiposDocumento_FK` FOREIGN KEY (`tipoDocumento`) REFERENCES `tiposDocumento` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;